### ISSUE TITLE
kolmogorov fit

### ISSUE THREAD

**Issue by EdwardBerman** [EdwardBerman/shopt#1]
Fitting a kolmogorov radial fit is taking unfeasibly long. I know that there is an added degree of difficulty in numerical integration but perhaps something else is causing a bottleneck? I have tried printing loss with every iteration and it seems to be working, but I am working it may never even converge enough to satisfy optim.jl's requirements.

**Comment by mcclearyj** [comment]
It does seem odd given that your pixel-grid fits, which have more degrees of freedom, converge in relatively short order.

**Comment by EdwardBerman** [comment]
Switching from Conjugate Gradient to LBFGS makes a big difference and Kolmogorov fits easier, however, I am comfortable sticking with Gaussian because as discussed, analytic fits do not well approximate the spikey nature of JWST PSFs to begin with so there is no use in adding a more expensive analytic fit
