### ISSUE TITLE
[JOSS] Missing references

### ISSUE THREAD

**Issue by aymgal** [EdwardBerman/shopt#10]
In the current state of the JOSS paper, I suggest to mention [`STARRED`](https://joss.theoj.org/papers/10.21105/joss.05340) as another efficient PSF reconstruction technique, as it has been shown to outperform other programs like PSFex (mentioned in the paper) and PSFr (which would need to be mentioned as well), and uses high the just-in-time compiled and auto-diff library JAX.

**Comment by aymgal** [comment]
Thanks @EdwardBerman !

However, STARRED has also been tested on JWST data, see this [example notebook](https://gitlab.com/cosmograil/starred/-/blob/main/notebooks/more_examples/7_JWST-PSF_reconstruction.ipynb?ref_type=heads). So I would simply remove the mention about the HST data validation, since the PSF modeling assumptions behind the STARRED method are not specific to a given telescope.

In addition, there seems to be a typo "...PSF models with competitive PSFr and PSFex..."

**Comment by EdwardBerman** [comment]
Ah, you are correct! Thank you @aymgal . I have fixed this with the following commit: [c388375](https://github.com/EdwardBerman/shopt/commit/c388375db62be6592a3d869ca16661b583b1d6a0)

**Comment by aymgal** [comment]
Thanks for the update, I close this issue!
