### ISSUE TITLE
[JOSS] Default output directory naming on macos

### ISSUE THREAD

**Issue by aymgal** [EdwardBerman/shopt#11]
The default naming of the output directory follows something like `2024-01-15T11:20:40.848`, but `:` characters are forbidden in macos path names (and are replaced by the `/` when displayed in a file explorer). Hence I would suggest not to use these characters but `-` or `_` instead.

**Comment by EdwardBerman** [comment]
This has been fixed with this  commit: [fbe320ab3cc4ddf4ae19daa8fa8a35819952880d](https://github.com/EdwardBerman/shopt/commit/fbe320ab3cc4ddf4ae19daa8fa8a35819952880d)
