### ISSUE TITLE
[JOSS] Paper Comments

### ISSUE THREAD

**Issue by jpierel14** [EdwardBerman/shopt#12]
The tool and paper look great! Here are some comments (mostly minor):

Summary
- 16: You say "...essentially point sources before their light passes through the atmosphere and telescope..." Obviously this is normally correct from the ground, but since this is specifically a JWST paper you may want to remove the atmosphere part, or change it to "...through the atmosphere (when observing from the ground) and telescope..."
- 23: Since you've restricted this to NIRCam for now, I'd add that in the last paragraph: "...tailored to JWST imaging" --> "...tailored to JWST NIRCam imaging"

Statement of Need
- 32: Don't need to redefine JWST here
- 33: Please put an "e.g.," in front of the COSMOS citation, NIRCam offers a lot more scientific opportunities than just that!
- 67: less --> fewer
- While I agree that figure 2 highlights the need for non-Gaussian PSF models, would it be possible to make this a 4-panel figure showing what happens if you use a 2D Gaussian? I know that people are doing this, and it may be nice to show how much larger the residuals are
- 131 x 131 pixels is very large...I would be surprised if your fitter is actually able to pull anything useful out at that scale. Even your Figure 2 is just showing 75 pixels, and already it's basically noise at the edge even on a log scale. Even at 20 pixels or so (radius) you should have almost all the flux, so I'm not sure if/why you would need to go all the way to 4-5 arc seconds. Contamination from other objects would be pretty common at that level as well.

State of the Field
- 87: spelling out PIFF (and PSFex for that matter) should go to the first mention in the previous section
- 95: Best to change "twenty-five years ago" to a year, so that in future years the line still makes sense
- 125: "takes up" --> "covers"

**Comment by EdwardBerman** [comment]
I've addressed all of these comments in my latest rendition of the draft, and I have rerendered the PDF in the JOSS issue. To illustrate the non Gaussian nature of the PSF, I added a comparison between an idealized WebbPSF forward model and a Gaussian approximation. Thank you for your insights!

**Comment by jpierel14** [comment]
Looks great!
