### ISSUE TITLE
[JOSS] Paper comments

### ISSUE THREAD

**Issue by kevinmicha** [EdwardBerman/shopt#7]
Hi,

Your [JOSS paper](https://github.com/openjournals/joss-papers/blob/joss.06144/joss.06144/10.21105.joss.06144.pdf) is pretty well written and clear! I have some minor suggestions, including fixing a few typos:

- I would remove the **Introduction** title, leaving simply **Summary**;
- Typo: 'unprecendented' (line 35);
- Typo: ‘biasses’ (line 67);
- Typo: ‘emblamatic’ (line 76);
- For the State of the Field section: I wonder how `ShOpt.jl` would compare with `PSFr` (https://github.com/sibirrer/psfr), which is quite recent and has been used for JWST data;
- **Beichman et al., 2012a** and **Beichman et al., 2012b** are exactly the same paper.

**Comment by EdwardBerman** [comment]
Thank you for your comments! I just pushed a paper with these typos and suggestions incorporated. I've seen your other issue as well, I'm planning on addressing that over my holiday break.

**Comment by kevinmicha** [comment]
Thank you @EdwardBerman! I'm happy with most of the changes, I'm just checking that you've replaced _emblamatic_ with _emblemetic_, but it's really minor.

Once you've changed that last aspect, this issue can be closed (feel free to do it).
