### ISSUE TITLE
[JOSS] Reproducibility: Figure 2 

### ISSUE THREAD

**Issue by kevinmicha** [EdwardBerman/shopt#8]
Hi,

I am trying to reproduce Figure 2 of the [paper](https://github.com/openjournals/joss-papers/blob/joss.06144/joss.06144/10.21105.joss.06144.pdf), and while it appears visually appealing, it would be helpful to have some additional clarifications:

1. It would be beneficial if you could specify in the repository (e.g. `README`) or on the GitHub site the precise JWST data file you downloaded and whether any modifications were made to the default `SExtractor` configuration files. 
2. Is it possible for users to generate Figure 2 by simply providing the exact catalog and using `TutorialNotebook.ipynb`, or would additional code be required?

Thanks a lot for your time!

**Comment by EdwardBerman** [comment]
Hello, thank you for these considerations! 

I've added a test catalog and a `SExtractor` config file, as well as some default `PIFF` and `PSFex` configs that I've been using for benchmarking. Figure 2 in the paper won't directly be made by `TutorialNotebook.ipynb`, only the renderings for the `ShOpt` PSFs at specified coordinates. However, I've gone ahead and updated the notebook with this new test catalog to make it easier to test functionality. Assuming you've gone through the instillation procedure and configured PyCall on your system, I have tested that the tutorial notebooks runs smoothly. Note that you will still have to modify the file paths to that of your system and such. In evaluating `ShOpt` I've used all of the wavelengths with the 30mas pixel scale at the provided link and I've added that as a note to the `README`.

**Comment by kevinmicha** [comment]
Hi @EdwardBerman, thank you for adding the requested files, clarifying some details and updating the notebook.

I was able to successfully run `ShOpt` for both `PCA` and `autoencoder` modes. The chi-squared pixel grid fit mode fails, but it is listed in the `README` Known Issues and Enhancements section, so this is fine to me.

I think I am ready to check all the items on the review list - but I just checked that _emblematic_ is still spelled incorrectly in the paper. When you fix that, would you close this issue and type `@editorialbot generate pdf` [here](https://github.com/openjournals/joss-reviews/issues/6144) so the PDF is regenerated? Thanks a lot!
